name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Prepare deployment package
      run: |
        mkdir -p deploy
        cp build/libs/*.jar deploy/

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AWS_SSH_HOST }}
        username: ${{ secrets.AWS_SSH_USER }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo systemctl stop myapp.service
          rm -rf /home/${{ secrets.AWS_SSH_USER }}/app/*
          cp -r deploy/* /home/${{ secrets.AWS_SSH_USER }}/app/
          echo "ENCRYPTION_KEY=${{ secrets.SECRET_KEY_SOURCE }}" > /home/${{ secrets.AWS_SSH_USER }}/app/.env
          sudo systemctl start myapp.service
